### ISSUE TITLE
Display password for template-generated OS

### ISSUE THREAD

**Issue by sdrose** [niwo/cloudstack-cli#20]
Hello!
I was wondering today, is it possible to have Cloudstack-cli display the generated Administrator password for a template-generated VM when it is first created?

I was looking at a process today for determining how to show the administrator password for a windows server IF the VM were created with a specified private key:

I know when I create a VM from the web portal of CloudPlatform, it will bring up a dialog box to show 1 time what the admin password is.   I think this feature would be quite helpful.

For anyone interested in the process of manually querying and decrypting the password to the Administrator's account, process follows:
cs server show win2012r2-ad01 | grep id

cs command getVMPassword id=“<VM ID Here>” >> win2012r2-ad01_enc_pw

Edit the file created above .. remove 1st line “---“
remove from 2nd line “encrypted password: “
1st char of the encrypted password should now be 1st char of 1st line.  Save file in this format.

openssl enc -base64 -d -A -in win2012r2-ad01_enc_pw -out win2012r2-ad01_pw_binary
openssl rsautl -decrypt -in win2012r2-ad01_enc_pw_binary -out win2012r2-ad01_plaintxt -inkey ~/.ssh/dave_cms4_keypair

Thank you!
-dave

**Comment by niwo** [comment]
Hi Dave,

Yes, this could be indeed helpful and it's possible to gather during VM deployment.

From [v1.5.8](https://github.com/niwo/cloudstack-cli/releases/tag/v1.5.8) on cloudstack-cli is going to ask you if you want to display the VM's password after creation.

Cheers,
Nik

**Comment by sdrose** [comment]
Error in cs server create, and did not display password, nor request to display password, in the cs stack create.

Here is the error message from the cs server create methodology:
drose$ cs server create centos7-test2 --iso=CentOs_7.2_x64 --offering=2vCPU-2660MHz-8GB-RAM --disk-offering=Custom --disk-size=80 --port-rules=":22, :80, :443" --zone=US-NEW-NUT-G-V-A-R-S-001  --networks=DRose-NUT --ip-address=10.1.0.23
Start deploying virtual machine...
Create virtual machine centos7-test2 : job completed 
Completed: 1 of 1 (153.0s)
Create port forwarding rules...
/Library/Ruby/Gems/2.0.0/gems/cloudstack-cli-1.5.8/lib/cloudstack-cli/commands/virtual_machine.rb:125:in `block in create': undefined method `list_virtual_machine' for #<CloudstackClient::Client:0x007f8a0aab40c8> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/cloudstack-cli-1.5.8/lib/cloudstack-cli/commands/virtual_machine.rb:124:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/cloudstack-cli-1.5.8/lib/cloudstack-cli/commands/virtual_machine.rb:124:in `create'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/cloudstack-cli-1.5.8/lib/cloudstack-cli/base.rb:17:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/cloudstack-cli-1.4.1/bin/cs:5:in `<top (required)>'
	from /usr/local/bin/cs:23:in `load'
	from /usr/local/bin/cs:23:in `<main>'
Daves-Mac:Dave-CMS2 drose$

**Comment by niwo** [comment]
Hi Dave,

Oh, no :-(
It's now fixed in [1.5.9](https://github.com/niwo/cloudstack-cli/releases/tag/v1.5.9)

Thanks,
Nik

**Comment by sdrose** [comment]
Hi Nik!
2 bugs still remain as I see on my Mac:
Bug 1:
Tried using the interactive cs server create command, and although it asked me to display or not display the password, the actual password never displayed, as you can see below.
 
drose$ cs server create centos7-test5 --iso=CentOs_7.2_x64 --offering=2vCPU-2660MHz-8GB-RAM --disk-offering=Custom --disk-size=80  --zone=US-NEW-NUT-G-V-A-R-S-001  --networks=DRose-NUT --ip-address=10.1.0.27
Start deploying virtual machine...
Create virtual machine centos7-test5 : job completed 
Completed: 1 of 1 (116.3s)
Finished.
Display password(s) for VM(s)? [y/N]: y
centos7-test5:  
Daves-Mac:Dave-CMS2 drose$ 

Bug 2:
When creating via the stack create methodology, there is no prompt to display the server.  To be honest, when I have my team provision a new VM, I always have them define it via the stack create YML file, even if it's only 1 VM, because then I can audit how they created the VM by reviewing the YML.  I don't really let them use the interactive command on the commandline.

drose$ cs stack create centos7_server_test01.yml 
Create stack CMS2-Demo-Account...
Create VM centos7-test3 : job completed 
Completed: 1 of 1 (112.3s)
Check for port forwarding rules...
Create port forwarding rules (:22) for VM centos7-test3 : job completed 
Create port forwarding rules (:80) for VM centos7-test3 : job completed 
Create port forwarding rules (:443) for VM centos7-test3 : job completed 
Completed: 3 of 3 (109.8s)
Finished.
drose$

here is my version info:
drose$ cs version
cloudstack-cli version 1.5.9
 (cloudstack_client version 1.4.3)

drose$ ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]

thanks for making awesome software!!
-dave

**Comment by sdrose** [comment]
Yes, you were correct and I was absolutely wrong.   Using a password-enabled template, I was able to display a password upon command-line VM generation, as shown below.  

drose$ cs server create centos7-test8  --offering=2vCPU-2660MHz-8GB-RAM --template=US_CENTOS_6.4_x64_v1.2.0_ESXi  --zone=US-NEW-NUT-G-V-A-R-S-001  --networks=DRose-NUT --ip-address=10.1.0.28
Start deploying virtual machine...
Create virtual machine centos7-test8 : job completed 
Completed: 1 of 1 (79.2s)
Finished.
Display password(s) for VM(s)? [y/N]: y
centos7-test8:  aI9yhfqcd
drose$ 

And thank you for adding the functionality to the stack create command!!!
-dave

**Comment by niwo** [comment]
Hi Dave,

Check out [1.5.10](https://github.com/niwo/cloudstack-cli/releases/tag/v1.5.10) - it does support the password display feature also for stacks.

**Comment by sdrose** [comment]
Oh. My bad.  Probably not a password enabled template.  Will check with one
on Monday ....
