### ISSUE TITLE
Creating via Stack

### ISSUE THREAD

**Issue by sdrose** [niwo/cloudstack-cli#7]
Hello Nik!
I was trying to modify the commandline arguments I have used to successfully create a single server instance, and I placed them into a custom-created .yml file.

Here is my commandline invocation, and the error I have received.  Below this, I will enter in the custom .YML file contents.

iMac:TGIF drose$ cs stack create test_stack.yml 
Create stack test_stack-a...
/usr/local/lib/ruby/gems/2.3.0/gems/cloudstack-cli-1.2.6/lib/cloudstack-cli/option_resolver.rb:4:in `vm_options_to_params': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/cloudstack-cli-1.2.6/lib/cloudstack-cli/commands/stack.rb:38:in `block (2 levels) in create'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cloudstack-cli-1.2.6/lib/cloudstack-cli/commands/stack.rb:11:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cloudstack-cli-1.2.6/lib/cloudstack-cli/commands/stack.rb:11:in `block in create'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cloudstack-cli-1.2.6/lib/cloudstack-cli/commands/stack.rb:10:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cloudstack-cli-1.2.6/lib/cloudstack-cli/commands/stack.rb:10:in `create'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cloudstack-cli-1.2.6/lib/cloudstack-cli/base.rb:16:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cloudstack-cli-1.2.6/bin/cs:5:in `<top (required)>'
	from /usr/local/bin/cs:23:in `load'
	from /usr/local/bin/cs:23:in `<main>'
iMac:TGIF drose$ 

---
  name: "test_stack-a"
  description: "Test Server Stack"
  version: "1.0"
  zone: "US-NEW-NUT-G-V-A-R-S-001"
  group: "my_server_stack"
  servers:
    -
      name:          "Test-Stack1-a"
      description:   "Test Server 1"
      iso:           "PlatesponBoot_W2K8R2"
      disk-offering: "Offering"
      disk-size:     "86"
      offering:      "1vCPU-1500Mhz-2GB-RAM"
      networks:      "ENVR_PROD1_VLAN2"
      ip-address:    "10.71.2.26"
    -
      name:          "Test-Stack1-b"
      description:   "Test Server 2"
      iso:           "PlatesponBoot_W2K8R2"
      disk-offering: "Offering"
      disk-size:     "86"
      offering:      "1vCPU-1500Mhz-2GB-RAM"
      networks:      "ENVR_PROD1_VLAN2"
      ip-address:    "10.71.2.27"

Thank you SO SO SO much, Nik!
-dave

**Comment by niwo** [comment]
Hi Dave,

So many bugs - incredibly :-(
Parsing the stack file should now work as expected (v1.2.7).

Please note that you have to use underscore in the YAML file (disk_size, ip_address etc.).

Hope this helps. Thanks for testing ;-)

Nik

**Comment by sdrose** [comment]
what is the argument for iso?

I use:  (Just the relevent portion of the .YML file)
servers:
    -
      name:          "Test-Stack1-a"
      description:   "Test Server 1"
      iso:           "PlateSpin_X2P"

and receive this error:

drose$ cs stack create test_stack.yml
Create stack test_stack-a...
Error: Template or ISO is required.
iMac:

**Comment by sdrose** [comment]
Hello Nik!
I have tried again, using version 1.3.0, to create via a stack file.  I still receive an error, relating to Disk Offering.  "Error: a disk offering is required when using iso."

drose$ cat stacktest1.yml 
---
  name: "stacktest1"
  description: "Test Server Stack"
  version: "1.0"
  zone: "US-NEW-NUT-G-V-A-R-S-001"
  group: "stacktest"
  servers:
    -
      name:          "stacktest1a"
      description:   "Test Server 1"
      iso:           "PlateSpin_X2P"
      disk_offering: "Custom"
      size:          "86"
      offering:      "1vCPU-1500Mhz-2GB-RAM"
      networks:      "Envr_PROD1_VLAN2"
      ip_address:    "10.71.2.28"
    -
      name:          "stacktest1b"
      description:   "Test Server 2"
      iso:           "PlateSpin_X2P"
      disk_offering: "custom"
      size:          "86"
      offering:      "1vCPU-1500Mhz-2GB-RAM"
      networks:      "Envr_PROD1_VLAN2"
      ip_address:    "10.71.2.29"

Command Issued:
drose$ cs stack create stacktest1.yml 
Create stack stacktest1...
Error: a disk offering is required when using iso.

**Comment by sdrose** [comment]
So I was looking in your repository, under the Options_resolver.rb file.  I saw in the area of line 124 the error message which is displayed when I try and run a cs stack create command.  Looking at the section of code, which I don't understand, I think I see the following ...

 def resolve_iso_for_vm_deployment
      unless options[:disk_offering_id]
        say "Error: a disk offering is required when using iso.", :red
        exit 1
      end
      resolve_iso
      options[:template_id] = options[:iso_id]

In the code where it asks for a resolver of the ISO name to ISO id ..
  Unless there is a disk_offer_id then say the error message.
Resolve the ISO name for an ISO_id to further the create command.

What I don't understand is how does the disk_offering name resolve to the disk_offering_id.  Specifically in this case, because a regular, singular create command does resolve the disk_offering name to id, but not in the instance of a stack command.

I'm sorry if my general questioning becomes a bother to you.  Thank you for anything you choose to give!  Your software is awesome, and even if I use it in individual commands, it is so much more helpful to me than using the portal.

Thank you!
-dave

**Comment by sdrose** [comment]
Just an update .... So, I had the option incorrect .. I used size instead of disk_size.  However, upon changing the option to disk_size, I still have the same problem.

**Comment by sdrose** [comment]
So, I had written the option as 'size' in the YAML config file because you have 
     size: instance["disk_size"],

on line 31 of the stack.rb file.

if I'm writing gibberish and non-sense, I apologize.  I don't understand Ruby, but the source is there, and I was looking to see if I can see something that looks wrong.  I figure the routine is basically the same as the routine in virtual machine create, so the two have to be roughly equivalent.  

When my car breaks down, I lift the hood and look there, too.  Even though I don't know how to fix an engine.  Same mentality, I guess.   :-)

-dave

**Comment by niwo** [comment]
Hi Dave,

This issue is currently still open - there is a bigger issue with the way the options are passed to the OptionParser functions.
I'll try to find a solution or work-around until the end of the week.

Just as a sidenote: within the yaml file (as with the cli option) you must use the parameter "disk_size".

Regards,
Nik

**Comment by sdrose** [comment]
Thank you for replying.  I was using say statements throughout the
option_parser module last night and saw what you say .. That values in
'options' from the stack.rb weren't visible from option_parser.rb.

Certainly, no rush. Thank you for any attention and effort you are able to
give. And, once again, I give my whole-hearted thanks!

-Dave

**Comment by niwo** [comment]
Hi Dave

This issue should be finally fixed with v1.3.1 - hope it works for you now.

Cheers,
Nik

**Comment by sdrose** [comment]
Thank you!  Thank you!!  Thank you!!!

-dave

**Comment by niwo** [comment]
Your welcome and thank you ;-)
